name: vector_db
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  uuid: ^4.3.3
  path: ^1.8.0
  http: ^0.13.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
